Repository Tunous/Dawn, pull requests merged in 2019-08, with the labels that each got.

#35 Using MediaStore to notify downloaded media
  app/src/main/java/me/saket/dank/notifs/MediaDownloadService.java
  app/src/main/java/me/saket/dank/utils/Intents.java
Labels: bug

#28 Make it possible to locally subscribe to /r/all
  CHANGELOG.md
  app/src/main/java/me/saket/dank/reddit/Reddit.kt
  app/src/main/java/me/saket/dank/reddit/jraw/JrawSubreddits.kt
  app/src/main/java/me/saket/dank/ui/subscriptions/SubscriptionRepository.java
Labels: 🎁 feature

#43 Upgrade compileSdk to API 28
  .circleci/config.yml
  app/src/main/java/me/saket/dank/ui/user/messages/InboxMessageType.java
  app/src/main/java/me/saket/dank/urlparser/RedditHostedVideoLink.java
  build.gradle
  markdownhints/build.gradle
Labels: 📚 dependencies

#41 Fix incorrect thumbnails on notifications of downloaded videos
  CHANGELOG.md
  app/src/main/java/me/saket/dank/utils/Urls.java
  app/src/test/java/me/saket/dank/utils/UrlParserTest.java
  app/src/test/java/me/saket/dank/utils/UrlsTest.java
Labels: 🐛 bug

#29 Display crosspost parent
  CHANGELOG.md
  app/src/main/java/me/saket/dank/ui/submission/SubmissionPageLayout.java
  app/src/main/java/me/saket/dank/ui/submission/adapter/SubmissionUiConstructor.kt
  app/src/main/java/me/saket/dank/ui/submission/events/SubmissionContentLinkClickEvent.java
  app/src/main/res/values/strings.xml
Labels: 🎁 feature

#54 Uprev Gradle to 5.6
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: 📚 dependencies

#52 Upgrade AndroidVideoCache to 2.7.1
  app/build.gradle
Labels: 📚 dependencies

#55 Uprev Android Gradle Plugin to 3.5.0
  build.gradle
Labels: 📚 dependencies

#42 Add feedback and source section to about screen
  CHANGELOG.md
  app/src/main/java/me/saket/dank/ui/preferences/adapter/AboutDankPreferencesConstructor.java
  app/src/main/res/values/userpreferences.xml
Labels: 🎁 feature

#57 MediaDownloadService: Run Glide clear on main thread
  CHANGELOG.md
  app/src/main/java/me/saket/dank/notifs/MediaDownloadService.java
Labels: 🐛 bug

#58 Fix animation of play/pause button
  app/src/main/java/me/saket/dank/ui/submission/SubmissionVideoControlsView.java
  app/src/main/java/me/saket/dank/utils/ReversibleAnimatedVectorDrawable.java
  app/src/main/res/drawable/avd_pause_to_play_white_24dp.xml
Labels: 🐛 bug

#49 Identify parents of comment by using colored lines
  CHANGELOG.md
  app/src/main/java/me/saket/dank/di/RootComponent.java
  app/src/main/java/me/saket/dank/di/UserPreferencesModule.java
  app/src/main/java/me/saket/dank/ui/preferences/adapter/LookAndFeelPreferencesConstructor.kt
  app/src/main/java/me/saket/dank/widgets/IndentedLayout.java
  app/src/main/res/values/colors.xml
  app/src/main/res/values/userpreferences.xml
Labels: 🎁 feature

#59 Bump Kotlin to 1.3.50
  build.gradle
Labels: 📚 dependencies
