Repository Tunous/Dawn, pull requests merged in 2020-01, with the labels that each got.

#109 Redirect user to internal browser when navigating to user profile
  app/src/main/java/me/saket/dank/deeplinks/DeepLinkHandlingActivity.java
  app/src/main/java/me/saket/dank/ui/preferences/DefaultWebBrowser.java
  app/src/main/java/me/saket/dank/ui/webview/WebViewActivity.java
Labels: 🐛 bug

#103 Fix occasional crash when entering login screen
  CHANGELOG.md
  app/src/main/java/me/saket/dank/reddit/jraw/JrawReddit.kt
Labels: 🐛 bug

#87 Large image previews
  CHANGELOG.md
  app/src/main/java/me/saket/dank/di/UserPreferencesModule.java
  app/src/main/java/me/saket/dank/ui/preferences/adapter/LookAndFeelPreferencesConstructor.kt
  app/src/main/java/me/saket/dank/ui/subreddit/uimodels/SubmissionItemDiffer.kt
  app/src/main/java/me/saket/dank/ui/subreddit/uimodels/SubredditSubmission.java
  app/src/main/java/me/saket/dank/ui/subreddit/uimodels/SubredditSubmissionImageStyle.kt
  app/src/main/java/me/saket/dank/ui/subreddit/uimodels/SubredditUiConstructor.java
  app/src/main/res/drawable/ic_image_style_large_20dp.xml
  app/src/main/res/drawable/ic_image_style_thumbnail_20dp.xml
  app/src/main/res/drawable/touchindicator_submission_image.xml
  app/src/main/res/layout/list_item_submission.xml
  app/src/main/res/layout/list_item_submission_content.xml
  app/src/main/res/layout/list_item_submission_content_left.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/userpreferences.xml
Labels: 🎁 feature, 🎨 design

#151 Resolve and silence lint warnings as appropriate
  app/src/main/java/me/saket/dank/ui/submission/RecyclerViewWithNestedProgrammaticScrolling.java
  app/src/main/java/me/saket/dank/ui/subscriptions/SubredditPickerSheetView.java
  markdownhints/build.gradle
Labels: 🔨 code
