Repository Tunous/Dawn, pull requests merged in 2020-09, with the labels that each got.

#313 Change repository order to prioritize jcenter above jitpack
  build.gradle
Labels: 🐛 bug, 📚 dependencies

#312 Support for reddit galleries
  CHANGELOG.md
  app/build.gradle
  app/src/main/java/me/saket/dank/AppUpdateActions.kt
  app/src/main/java/me/saket/dank/DankApplication.java
  app/src/main/java/me/saket/dank/cache/CachePreFiller.java
  app/src/main/java/me/saket/dank/data/LinkMetadataRepository.kt
  app/src/main/java/me/saket/dank/ui/media/BaseMediaViewerFragment.java
  app/src/main/java/me/saket/dank/ui/media/MediaAlbumViewerActivity.java
  app/src/main/java/me/saket/dank/ui/media/MediaImageFragment.java
  app/src/main/java/me/saket/dank/ui/media/MediaLinkWithStartingPosition.java
  app/src/main/java/me/saket/dank/ui/submission/SubmissionImageLoader.java
  app/src/main/java/me/saket/dank/ui/submission/SubmissionPageLayout.java
  app/src/main/java/me/saket/dank/ui/submission/adapter/ImageWithMultipleVariants.kt
  app/src/main/java/me/saket/dank/ui/submission/adapter/SubmissionContentLinkUiConstructor.java
  app/src/main/java/me/saket/dank/ui/subreddit/uimodels/SubredditUiConstructor.java
  app/src/main/java/me/saket/dank/urlparser/ExternalLink.java
  app/src/main/java/me/saket/dank/urlparser/GenericMediaLink.java
  app/src/main/java/me/saket/dank/urlparser/GfycatLink.java
  app/src/main/java/me/saket/dank/urlparser/GfycatUnresolvedLink.java
  app/src/main/java/me/saket/dank/urlparser/GiphyLink.java
  app/src/main/java/me/saket/dank/urlparser/ImgurAlbumLink.java
  app/src/main/java/me/saket/dank/urlparser/ImgurLink.java
  app/src/main/java/me/saket/dank/urlparser/Link.java
  app/src/main/java/me/saket/dank/urlparser/Link.kt
  app/src/main/java/me/saket/dank/urlparser/MediaAlbumLink.kt
  app/src/main/java/me/saket/dank/urlparser/MediaLink.java
  app/src/main/java/me/saket/dank/urlparser/MediaLink.kt
  app/src/main/java/me/saket/dank/urlparser/RedditCommentLink.java
  app/src/main/java/me/saket/dank/urlparser/RedditGalleryLink.kt
  app/src/main/java/me/saket/dank/urlparser/RedditHostedVideoLink.java
  app/src/main/java/me/saket/dank/urlparser/RedditSubmissionLink.java
  app/src/main/java/me/saket/dank/urlparser/RedditSubredditLink.java
  app/src/main/java/me/saket/dank/urlparser/RedditUserLink.java
  app/src/main/java/me/saket/dank/urlparser/RedgifsUnresolvedLink.java
  app/src/main/java/me/saket/dank/urlparser/StreamableLink.java
  app/src/main/java/me/saket/dank/urlparser/StreamableUnresolvedLink.java
  app/src/main/java/me/saket/dank/urlparser/UrlParser.java
  app/src/main/java/me/saket/dank/urlparser/UrlParserConfig.java
  app/src/main/java/me/saket/dank/utils/ImageWithMultipleVariants.kt
  app/src/main/java/me/saket/dank/walkthrough/SyntheticSubmission.kt
Labels: 🎁 feature

#319 Trim spaces in parsed links
  CHANGELOG.md
  app/src/main/java/me/saket/dank/utils/markdown/markwon/MarkwonBasedMarkdownRenderer.java
  app/src/test/java/me/saket/dank/utils/markdown/markwon/MarkwonBasedMarkdownRendererTest.java
Labels: 🐛 bug

#326 Make draft release workflow manual
  .github/workflows/release_draft.yml
Labels: 🔨 code
