Repository Tunous/Dawn, pull requests merged in 2020-05, with the labels that each got.

#182 Submission title selection
  CHANGELOG.md
  app/src/main/java/me/saket/dank/ui/submission/SubmissionTitleSpan.kt
  app/src/main/java/me/saket/dank/ui/submission/adapter/SubmissionCommentsHeader.java
  app/src/main/java/me/saket/dank/ui/submission/adapter/SubmissionUiConstructor.kt
  app/src/main/java/me/saket/dank/widgets/SelectionLimitingTextView.kt
  app/src/main/res/layout/list_item_submission_comments_header.xml
Labels: 🎁 feature

#178 Selftext selection
  CHANGELOG.md
  app/src/main/java/me/saket/dank/ui/submission/SubmissionPageLayout.java
  app/src/main/java/me/saket/dank/ui/submission/adapter/SubmissionCommentsHeader.java
  app/src/main/res/layout/list_item_submission_comments_header.xml
Labels: 🎁 feature

#185 Release workflow
  .github/workflows/debug.yml
  .github/workflows/release.yml
  signing/cleanup.sh
Labels: 🔨 code

#184 Release 0.9.0
  CHANGELOG.md
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/16.txt
Labels: :checkered_flag: release

#196 Force logout all users
  app/src/main/java/me/saket/dank/ui/user/UserSessionRepository.java
Labels: 🐛 bug

#198 Release 0.9.1
  CHANGELOG.md
Labels: 🏁 release

#200 Add workflows related to release automation
  .github/workflows/changelog_reminder.yml
  .github/workflows/release.yml
  .github/workflows/release_draft.yml
Labels: 🎁 feature
