Repository Tunous/Dawn, pull requests merged in 2020-04, with the labels that each got.

#138 Switch to on-device link unfurler
  .idea/kotlinCodeInsightSettings.xml
  app/build.gradle
  app/src/main/java/me/saket/dank/cache/CachePreFiller.java
  app/src/main/java/me/saket/dank/data/LinkMetadataRepository.java
  app/src/main/java/me/saket/dank/data/LinkMetadataRepository.kt
  app/src/main/java/me/saket/dank/di/RootModule.java
  app/src/main/java/me/saket/dank/ui/submission/adapter/SubmissionContentLinkUiConstructor.java
  app/src/test/java/me/saket/dank/ui/subreddit/CachePreFillerShould.java
  build.gradle
  linkunfurler/.gitignore
  linkunfurler/build.gradle
  linkunfurler/proguard-rules.pro
  linkunfurler/src/main/AndroidManifest.xml
  linkunfurler/src/main/java/me/thanel/dawn/linkunfurler/LinkMetadata.kt
  linkunfurler/src/main/java/me/thanel/dawn/linkunfurler/LinkMetadataReader.kt
  linkunfurler/src/main/java/me/thanel/dawn/linkunfurler/LinkUnfurler.kt
  linkunfurler/src/main/java/me/thanel/dawn/linkunfurler/readers/GenericLinkMetadataReader.kt
  linkunfurler/src/main/java/me/thanel/dawn/linkunfurler/readers/PlayStoreLinkMetadataReader.kt
  markdownhints/build.gradle
  settings.gradle
Labels: 🎁 feature

#72 Use GitHub Actions
  .circleci/config.yml
  .github/ci-gradle.properties
  .github/workflows/debug.yml
  README.md
  checksum.sh
Labels: 🔨 code

#152 Upgrade Gradle to 6.2.1
  .github/workflows/debug.yml
  .github/workflows/validate_wrapper.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
Labels: 📚 dependencies

#145 Wrap comment byline when it is too long to fit in one line
  app/build.gradle
  app/src/main/java/me/saket/dank/DankApplication.java
  app/src/main/java/me/saket/dank/ui/submission/SubmissionCommentTreeUiConstructor.java
  app/src/main/java/me/saket/dank/walkthrough/SyntheticSubmission.kt
  app/src/main/res/layout/list_item_submission_comment.xml
  app/src/test/java/me/saket/dank/ui/comments/SubmissionCommentTreeBaseTest.kt
  app/src/test/java/me/saket/dank/ui/comments/SubmissionCommentTreeBylineTest.kt
  gradle.properties
Labels: 🎁 feature
