Repository Tunous/Dawn, pull requests merged in 2021-01, with the labels that each got.

#357 Remove bugsnag
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/me/saket/dank/DankApplication.java
  app/src/main/java/me/saket/dank/analytics/AnalyticsDaggerModule.java
  app/src/main/java/me/saket/dank/analytics/BugsnagCrashReporter.java
  app/src/main/java/me/saket/dank/analytics/CrashReporter.java
  app/src/main/java/me/saket/dank/analytics/package-info.java
  app/src/main/java/me/saket/dank/data/LinkMetadataRepository.kt
  app/src/main/java/me/saket/dank/di/RootComponent.java
  app/src/main/java/me/saket/dank/ui/user/UserAuthListener.java
  app/src/test/java/me/saket/dank/ui/user/UserAuthListenerTest.java
Labels: 💥 bugsnag, 📚 dependencies

#363 Fix Gfycat extractor
  app/src/main/java/me/saket/dank/ui/media/gfycat/GfycatResponse.java
Labels: 🐛 bug

#372 Bulk dependency upgrades
  app/build.gradle
  app/src/main/java/me/saket/dank/deeplinks/DeepLinkHandlingActivity.java
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  markdownhints/build.gradle
  markdownhints/src/main/java/me/saket/dank/markdownhints/MarkdownNodeTreeVisitor.java
  markdownhints/src/main/java/me/saket/dank/markdownhints/RedditSuperscriptExtension.java
Labels: 📚 dependencies

#375 Fix uses of auto-value-moshi
  app/src/main/java/me/saket/dank/data/CachedResolvedLinkInfo.java
  app/src/main/java/me/saket/dank/data/UnfurlLinkResponse.java
  app/src/main/java/me/saket/dank/reply/ReplyDraft.java
  app/src/main/java/me/saket/dank/ui/giphy/GiphySearchResponse.java
  app/src/main/java/me/saket/dank/ui/media/ImgurAlbumResponse.java
  app/src/main/java/me/saket/dank/ui/media/ImgurImage.java
  app/src/main/java/me/saket/dank/ui/media/ImgurImageResponse.java
  app/src/main/java/me/saket/dank/ui/media/ImgurUploadResponse.java
  app/src/main/java/me/saket/dank/ui/media/gfycat/GfycatOauthResponse.java
  app/src/main/java/me/saket/dank/ui/media/gfycat/GfycatResponse.java
  app/src/main/java/me/saket/dank/ui/preferences/TypefaceResource.java
  app/src/main/java/me/saket/dank/ui/submission/AuditedCommentSort.java
  app/src/main/java/me/saket/dank/ui/user/UserSubreddit.java
  app/src/main/java/me/saket/dank/urlparser/GenericMediaLink.java
  app/src/main/java/me/saket/dank/urlparser/GfycatLink.java
  app/src/main/java/me/saket/dank/urlparser/GiphyLink.java
  app/src/main/java/me/saket/dank/urlparser/ImgurAlbumLink.java
  app/src/main/java/me/saket/dank/urlparser/ImgurLink.java
  app/src/main/java/me/saket/dank/urlparser/LinkMetadata.java
  app/src/main/java/me/saket/dank/urlparser/StreamableLink.java
  app/src/main/java/me/saket/dank/utils/DankSubmissionRequest.java
  app/src/main/java/me/saket/dank/utils/TimeInterval.java
Labels: 🔨 code

#382 Improve commonmark dependency resolution logic
  build.gradle
Labels: 🔨 code
